#!/bin/sh
#
# Restore backlight levels

case "$1" in
	start)
	for index in $(seq 0 1); do
		if [ -e /etc/blstate.$index ]; then
			cat /etc/blstate.$index >/sys/class/backlight/pwm-backlight.$index/brightness
		fi
	done
	;;
	*)
	echo $"Usage: $0 {start}"
	exit 1
esac

exit $?
