#!/bin/sh
#
# execute /etc/rc.local 
#

case "$1" in
  start)
 	echo "Executing /etc/rc.local..."
	/etc/rc.local
	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

